wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.10
      5: 0.10.29
      8:
      - 1
      - 5
learning_rate:
  desc: null
  value: 0.01
